export { default as Nav } from "./Components/Nav";
export { default as News } from "./Components/News";
export { default as Footer } from "./Components/Footer";
export { default as Earn } from "./Components/Earn";
export { default as Signin } from "./Components/Signin";
export { default as Signup } from "./Components/Signup";
export { default as Dashboard } from "./Components/Dashboard";
export { default as Opinion } from "./Components/Opinion";
export { default as Discussion } from "./Components/Discussion";
