export { default as Nav } from "./assets/Components/Navnts/Nav";
export { default as News } from "./assets/Components/Newsts/News";
export { default as Footer } from "./assets/Components/Footer/Footer";
export { default as Earn } from "./assets/Components/Earnts/Earn";
export { default as Signin } from "./assets/Components/Signin/Signin";
export { default as Signup } from "./assets/Components/Signup/Signup";
export { default as Dashboard } from "./assets/Components/Dashboardshboard";
export { default as Opinion } from "./assets/Components/OpinionOpinion";
export { default as Discussion } from "./assets/Components/Discussioncussion";
