export { default as Nav } from "./assets/Components/Nav";
export { default as News } from "./assets/Components/News";
export { default as Footer } from "./assets/Components/Footer";
export { default as Earn } from "./assets/Components/Earn";
export { default as Signin } from "./assets/Components/Signin";
export { default as Signup } from "./assets/Components/Signup";
export { default as Dashboard } from "./assets/Components/Dashboard";
export { default as Opinion } from "./assets/Components/Opinion";
export { default as Discussion } from "./assets/Components/Discussion";
